# Generated by Django 3.2.16 on 2022-10-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
