# Generated by Django 3.2.16 on 2022-10-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Premium'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
