# Generated by Django 3.2.16 on 2022-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20221016_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseAnswer',
        ),
        migrations.DeleteModel(
            name='ExerciseQuestion',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='premium',
        ),
        migrations.AddField(
            model_name='lesson',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Premium'),
        ),
    ]
